version: "3.7"

services:
  pg:
    image: postgres:12.1
    # The `always` option below will make sure this
    # container is started when you turn on your machine,
    # so you don't have to worry about it everytime.
    restart: always
    ports:
      # The 127.0.0.1 prefix makes sure this instance
      # cannot be accessed externally, so it is ok
      # for this instante to have no password.
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${DB_NAME:-ksql}

  mysql:
    image: mariadb:10.8
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: mysql
      MARIADB_DATABASE: ksql

  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    ports:
      - "127.0.0.1:1433:1433"
      - "127.0.0.1:1434:1434"
    environment:
      SA_PASSWORD: "Sqls3rv3r"
      ACCEPT_EULA: "Y"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    # The `always` option below will make sure this
    # container is started when you turn on your machine,
    # so you don't have to worry about it everytime.
    restart: always
    ports:
      # The 127.0.0.1 prefix makes sure this instance
      # cannot be accessed externally, so it is ok
      # for this instante to have no password.
      - "127.0.0.1:1433:1433"
    environment:
      - SA_PASSWORD=Sqls3rv3r
      - ACCEPT_EULA=Y
